-- MySQL Script generated by MySQL Workbench
-- Sun Dec 10 22:14:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ferreteria-construmanta-p
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ferreteria-construmanta-p
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ferreteria-construmanta-p` DEFAULT CHARACTER SET utf8 ;
USE `ferreteria-construmanta-p` ;

-- -----------------------------------------------------
-- Table `ferreteria-construmanta-p`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria-construmanta-p`.`usuario` ;

CREATE TABLE IF NOT EXISTS `ferreteria-construmanta-p`.`usuario` (
  `id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `nombre_completo` VARCHAR(255) NOT NULL,
  `correo_electronico` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(24) NOT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `es_admin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo_electronico_UNIQUE` (`correo_electronico` ASC) VISIBLE,
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria-construmanta-p`.`sugerencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria-construmanta-p`.`sugerencia` ;

CREATE TABLE IF NOT EXISTS `ferreteria-construmanta-p`.`sugerencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` CHAR(36) NOT NULL,
  `mensaje` TEXT(1024) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sugerencia_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_sugerencia_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ferreteria-construmanta-p`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria-construmanta-p`.`estado_reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria-construmanta-p`.`estado_reserva` ;

CREATE TABLE IF NOT EXISTS `ferreteria-construmanta-p`.`estado_reserva` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria-construmanta-p`.`estado_herramienta_maquina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria-construmanta-p`.`estado_herramienta_maquina` ;

CREATE TABLE IF NOT EXISTS `ferreteria-construmanta-p`.`estado_herramienta_maquina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria-construmanta-p`.`herramienta_maquina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria-construmanta-p`.`herramienta_maquina` ;

CREATE TABLE IF NOT EXISTS `ferreteria-construmanta-p`.`herramienta_maquina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_articulo` VARCHAR(45) NOT NULL,
  `descripcion` TEXT(400) NULL DEFAULT NULL,
  `precio_alquiler` DECIMAL(10,2) NOT NULL,
  `cantidad_disponible` INT NOT NULL,
  `estado_herramienta_maquina_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_herramienta_maquina_estado_herramienta_maquina1_idx` (`estado_herramienta_maquina_id` ASC) VISIBLE,
  CONSTRAINT `fk_herramienta_maquina_estado_herramienta_maquina1`
    FOREIGN KEY (`estado_herramienta_maquina_id`)
    REFERENCES `ferreteria-construmanta-p`.`estado_herramienta_maquina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria-construmanta-p`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria-construmanta-p`.`reserva` ;

CREATE TABLE IF NOT EXISTS `ferreteria-construmanta-p`.`reserva` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` CHAR(36) NOT NULL,
  `herramienta_maquina_id` INT NOT NULL,
  `fecha_inicio` TIMESTAMP NOT NULL DEFAULT NOW(),
  `fecha_fin` DATETIME NOT NULL,
  `cantidad` INT NOT NULL,
  `estado_reserva_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reserva_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_reserva_estado_reserva1_idx` (`estado_reserva_id` ASC) VISIBLE,
  INDEX `fk_reserva_herramienta_maquina1_idx` (`herramienta_maquina_id` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ferreteria-construmanta-p`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_estado_reserva1`
    FOREIGN KEY (`estado_reserva_id`)
    REFERENCES `ferreteria-construmanta-p`.`estado_reserva` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_herramienta_maquina1`
    FOREIGN KEY (`herramienta_maquina_id`)
    REFERENCES `ferreteria-construmanta-p`.`herramienta_maquina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria-construmanta-p`.`estado_venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria-construmanta-p`.`estado_venta` ;

CREATE TABLE IF NOT EXISTS `ferreteria-construmanta-p`.`estado_venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria-construmanta-p`.`venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria-construmanta-p`.`venta` ;

CREATE TABLE IF NOT EXISTS `ferreteria-construmanta-p`.`venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` CHAR(36) NOT NULL,
  `fecha_emision` TIMESTAMP NOT NULL DEFAULT NOW(),
  `total_venta` DECIMAL(10,2) NOT NULL,
  `enviar_factura` TINYINT NOT NULL DEFAULT 0,
  `estado_venta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_factura_estado_factura1_idx` (`estado_venta_id` ASC) VISIBLE,
  INDEX `fk_venta_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_factura_estado_factura1`
    FOREIGN KEY (`estado_venta_id`)
    REFERENCES `ferreteria-construmanta-p`.`estado_venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ferreteria-construmanta-p`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria-construmanta-p`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria-construmanta-p`.`categoria` ;

CREATE TABLE IF NOT EXISTS `ferreteria-construmanta-p`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(48) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `categoria_UNIQUE` (`categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria-construmanta-p`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria-construmanta-p`.`producto` ;

CREATE TABLE IF NOT EXISTS `ferreteria-construmanta-p`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(128) NOT NULL,
  `clave_producto` VARCHAR(128) NOT NULL,
  `marca` VARCHAR(64) NOT NULL,
  `descripcion` TEXT(400) NULL DEFAULT NULL,
  `precio` FLOAT(2) NOT NULL,
  `cantidad` INT NOT NULL,
  `url_imagen` VARCHAR(45) NULL DEFAULT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`, `clave_producto`),
  UNIQUE INDEX `nombre_producto_UNIQUE` (`nombre_producto` ASC) VISIBLE,
  INDEX `fk_producto_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `ferreteria-construmanta-p`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria-construmanta-p`.`detalle_venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria-construmanta-p`.`detalle_venta` ;

CREATE TABLE IF NOT EXISTS `ferreteria-construmanta-p`.`detalle_venta` (
  `id` INT NOT NULL,
  `factura_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `cantidad_vendida` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_factura_producto1_idx` (`producto_id` ASC) VISIBLE,
  INDEX `fk_detalle_factura_factura1_idx` (`factura_id` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_factura_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `ferreteria-construmanta-p`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_factura_factura1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `ferreteria-construmanta-p`.`venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria-construmanta-p`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria-construmanta-p`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `ferreteria-construmanta-p`.`proveedor` (
  `id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `NIT` INT NOT NULL,
  `nombre_proveedor` VARCHAR(255) NOT NULL,
  `direccion_proveedor` VARCHAR(255) NOT NULL,
  `telefono_proveedor` VARCHAR(24) NOT NULL,
  `correo_proveedor` VARCHAR(255) NOT NULL,
  `telefono_vendedor` VARCHAR(24) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `NIT_UNIQUE` (`NIT` ASC) VISIBLE,
  UNIQUE INDEX `nombre_proveedor_UNIQUE` (`nombre_proveedor` ASC) VISIBLE,
  UNIQUE INDEX `correo_proveedor_UNIQUE` (`correo_proveedor` ASC) VISIBLE,
  UNIQUE INDEX `telefono_proveedor_UNIQUE` (`telefono_proveedor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria-construmanta-p`.`categoria_has_proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria-construmanta-p`.`categoria_has_proveedor` ;

CREATE TABLE IF NOT EXISTS `ferreteria-construmanta-p`.`categoria_has_proveedor` (
  `categoria_id` INT NOT NULL,
  `proveedor_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`categoria_id`, `proveedor_id`),
  INDEX `fk_categoria_has_proveedor_proveedor1_idx` (`proveedor_id` ASC) VISIBLE,
  INDEX `fk_categoria_has_proveedor_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_has_proveedor_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `ferreteria-construmanta-p`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria_has_proveedor_proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `ferreteria-construmanta-p`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria-construmanta-p`.`producto_has_proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ferreteria-construmanta-p`.`producto_has_proveedor` ;

CREATE TABLE IF NOT EXISTS `ferreteria-construmanta-p`.`producto_has_proveedor` (
  `producto_id` INT NOT NULL,
  `proveedor_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`producto_id`, `proveedor_id`),
  INDEX `fk_producto_has_proveedor_proveedor1_idx` (`proveedor_id` ASC) VISIBLE,
  INDEX `fk_producto_has_proveedor_producto1_idx` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_producto_has_proveedor_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `ferreteria-construmanta-p`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_proveedor_proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `ferreteria-construmanta-p`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
